Skip cell annotation if cell annotation sources empty
bioinfocz/scdrake pull request #3
Opened 2023-09-15 16:46 UTC by vucinick

**Fixes issue #2**

## Description of the fix
This fix addresses the issue where declaring `CELL_ANNOTATION_SOURCES: null` in the `02_norm_clustering.yaml` configuration file would result in the pipeline failing. The reason was that it creates an empty list which isn't null.

The fix now checks the length of the list, and if it's 0, it skips the cell annotation step, ensuring the expected behavior mentioned in the issue. Additionally, I've updated the relevant Rmd files to determine whether to include the cell annotation part in the report.

I've also made an addition to the vignette to document that there is an option to use null for cell annotation sources. This can be particularly useful for cases involving non-model organisms with limited annotation sources.

Please review and merge this pull request to resolve the issue. Thank you!

2023-09-18 06:18 UTC, gorgitko commented
Hey @vucinick, thank you for the PR.

While your solution is valid, I think easier would be to remove these lines https://github.com/bioinfocz/scdrake/blob/d92f86e8af97b4668b2be44118734e83c1ab68bd/R/config_process_common.R#L406-L408
and `CELL_ANNOTATION_SOURCES` will stay `NULL` after the config load.

I think the reason why this param is changed to an empty list is that the cell annotation subplan was earlier https://github.com/bioinfocz/scdrake/blob/e10c442605ac21364539c27689dba28f28ab93f3/R/plans_single_sample.R#L328-L331
not separated from the main plan, but there couldn't be just `NULL`, because `drake` is then not able to dynamic map over it (`cell_annotation_params`).

---

It's currently not documented, but you can run unit and end-to-end tests through https://github.com/bioinfocz/scdrake/blob/main/dev/run_tests.R:

```shell
docker exec -it -u rstudio -w /home/rstudio/scdrake_source <container> \
  r --interactive -L /usr/local/lib/R/site-library -t dev/run_tests.R \
  --output-dir /home/rstudio/shared/scdrake_run_tests \
  --output-dir-pipeline-tests /home/rstudio/shared/scdrake_run_tests/pipeline_outputs
```

It assumes your `scdrake` local repo is mounted as `/home/rstudio/scdrake_source`

Check `Rscript dev/run_tests.R -h` for more options.

2023-09-18 06:19 UTC, gorgitko requested changes

2023-09-27 14:37 UTC, vucinick commented on vignettes/stage_norm_clustering.Rmd
> +- `reference_type: "celldex"` (character scalar: `"celldex"` | `"file"` | `"null"`): type of the reference dataset.
Apologies, you are right, I corrected it in [981f66b](https://github.com/bioinfocz/scdrake/pull/3/commits/981f66be90f4ec68bb1a4f8c0fe7508750a1a5b9) commit.

2023-09-27 14:57 UTC, vucinick commented
Hi @gorgitko,
I managed to fix the issue with your proposed solution with a modification. I am unsure if I correctly interpreted the pipeline, but I had to remove creation of an empty list in two files:
https://github.com/bioinfocz/scdrake/blob/d92f86e8af97b4668b2be44118734e83c1ab68bd/R/config_process_common.R#L406-L408
and
https://github.com/bioinfocz/scdrake/blob/d92f86e8af97b4668b2be44118734e83c1ab68bd/R/cell_annotation.R#L13-L15
The empty file creation in R/cell_annotation.R seemed unnecessary with my solution, so I remove it in `cell_annotation_params_fn`.

The main part would be in R/config_process_single_sample.R, where I added the part to checks if the `CELL_ANNOTATION_SOURCES` is `null` or not. Depending on this, it either skips or continues with preparing the `cell_annotation_sources_params`.
As I am writing this, I realized I missed this part in R/config_process_integration.R. I will add it later, if this solution is correct.

I ran the test for the single_sample pipeline, and it correctly creates normalization reports without the cell annotation :grin:.

2023-10-01 09:42 UTC, gorgitko commented
Hi @vucinick, looks good! Please, add the relevant part also to the `R/config_process_integration.R`. Thanks!

2023-10-05 10:05 UTC, gorgitko approved these changes

2023-10-05 10:05 UTC, merged